version: '3.3'
services:
  rest_api:
    container_name: rest_api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env-sample
    environment:
      - DB_HOST=litestar_db
    links:
      - litestar_db
    command: bash -c "
      poetry run litestar database upgrade head --no-prompt
      && poetry run litestar run --host 0.0.0.0 --port 8000
      "
    ports:
      - '8000:8000'
    expose:
      - 8080
    depends_on:
      - litestar_db

  litestar_db:
    container_name: litestar_db
    image: postgres:16.4
    restart: always
    env_file:
      - .env-db-sample
    ports:
      - "5432:5432"
#    volumes:
#      - ./config/pg_init:/docker-entrypoint-initdb.d
#      - ./pg_db:/var/lib/postgresql/data


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env-db-sample
    ports:
      - "5050:80"
#    volumes:
#      - ./pgadmin:/var/lib/pgadmin
#      - ./pg_backups:/tmp
    depends_on:
      - litestar_db
