[tool.poetry]
name = "task2"
version = "0.1.0"
description = ""
authors = ["Tima <timapigolev@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
python-dotenv = "^1"
litestar = { extras = ["standard"], version = "^2" }
litestar-granian = "0.12.2"
litestar-asyncpg = "0.3.0"
advanced-alchemy = "1.4.1"
msgspec = "^0.18.6"
pydantic = "2.11.4"
pydantic_core = "2.33.2"
SQLAlchemy = "2.0.40"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
